import AppKit
import Charts
import SwiftUI
import UniformTypeIdentifiers

func plural(_ n: Int, _ word: String) -> String { "\(n) \(word)\(n == 1 ? "" : "s")" }

func sourceLabels(_ csv: String) -> String {
    csv.split(separator: ",").compactMap { Source(rawValue: String($0))?.label }.joined(separator: ", ")
}

// MARK: - Overview

struct OverviewPage: View {
    @EnvironmentObject var app: AppState
    @State private var metric: Metric = .all

    var body: some View {
        let d = app.data
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                ProviderGrid()

                LazyVGrid(columns: Array(repeating: GridItem(.flexible(), spacing: 12), count: 4), spacing: 12) {
                    StatTile(title: "Total tokens", value: Fmt.tokens(d.totals.all),
                             detail: "in \(Fmt.tokens(d.totals.input)) · out \(Fmt.tokens(d.totals.output)) · cache \(Fmt.tokens(d.totals.cacheRead + d.totals.cacheWrite))",
                             symbol: "number", help: "Input + output + cache read + cache write tokens")
                    StatTile(title: "Est. API cost", value: Fmt.cost(d.totals.cost),
                             detail: "Claude Code at API list prices", symbol: "dollarsign.circle",
                             help: "pi and omp report their own cost. Claude Code usage is priced at pay-as-you-go API rates — not what a subscription bills.")
                    StatTile(title: "Requests", value: d.totals.requests.formatted(),
                             detail: d.totals.errors > 0 ? plural(d.totals.errors, "error") : "no errors", symbol: "arrow.left.arrow.right",
                             help: "Model responses (including sub-agent and advisor calls)")
                    StatTile(title: "Sessions", value: "\(d.totals.sessions)",
                             detail: "\(d.sessions.filter(\.isActive).count) active now", symbol: "rectangle.stack")
                    StatTile(title: "Output tokens", value: Fmt.tokens(d.totals.output),
                             detail: d.totals.reasoning > 0 ? "incl. \(Fmt.tokens(d.totals.reasoning)) reasoning" : "generated by the models",
                             symbol: "text.cursor")
                    StatTile(title: "Cache hit rate", value: String(format: "%.1f%%", d.totals.cacheHitRate * 100),
                             detail: "of prompt tokens read from cache", symbol: "bolt.horizontal",
                             help: "cache read ÷ (input + cache read + cache write)")
                    StatTile(title: "Today", value: Fmt.tokens(d.today.all),
                             detail: "\(Fmt.cost(d.today.cost)) · \(plural(d.today.requests, "request"))", symbol: "sun.max")
                    StatTile(title: "Last hour", value: Fmt.tokens(d.lastHour.all),
                             detail: "\(Fmt.cost(d.lastHour.cost)) · \(plural(d.lastHour.requests, "request"))", symbol: "flame")
                }

                Card(title: app.range == .today ? "Usage by hour" : "Usage by day", subtitle: "Stacked by model · hover a bar for the breakdown") {
                    Picker("Metric", selection: $metric) {
                        ForEach(Metric.allCases) { Text($0.rawValue).tag($0) }
                    }
                    .pickerStyle(.segmented)
                    .labelsHidden()
                    .frame(maxWidth: 440)
                    UsageChart(points: d.buckets, metric: metric, hourly: app.range == .today)
                }

                HStack(alignment: .top, spacing: 16) {
                    Card(title: "Model share", subtitle: "\(metric.rawValue) · hover a slice") {
                        ModelShareDonut(models: d.models, metric: metric)
                    }
                    Card(title: "By agent", subtitle: "Tokens and estimated cost per tool") {
                        RankedBars(items: d.bySource.map {
                            .init(id: $0.source.rawValue, label: $0.source.label, value: Double($0.totals.all),
                                  valueText: "\(Fmt.tokens($0.totals.all)) · \(Fmt.cost($0.totals.cost))",
                                  detail: plural($0.totals.sessions, "session"),
                                  color: Palette.sourceColors[$0.source] ?? Palette.other)
                        }) { item in
                            app.sources = [Source(rawValue: item.id) ?? .claude]
                        }
                        Text("Click an agent to filter the dashboard").font(.caption2).foregroundStyle(.tertiary)
                    }
                }

                Card(title: "When you work", subtitle: "Tokens by weekday and hour (local time)") {
                    ActivityHeatmap(cells: d.heat)
                }

                HStack(alignment: .top, spacing: 16) {
                    Card(title: "Top projects", subtitle: "Click to see their sessions") {
                        RankedBars(items: d.projects.prefix(8).map {
                            .init(id: $0.path, label: $0.displayName ?? $0.name, value: Double($0.tokens),
                                  valueText: Fmt.tokens($0.tokens), detail: plural($0.sessions, "session"), help: $0.path)
                        }) { app.showSessions(matching: $0.label) }
                    }
                    Card(title: "Top tools", subtitle: "Tool calls made by the agents") {
                        RankedBars(items: d.tools.prefix(8).map {
                            .init(id: $0.name, label: $0.name, value: Double($0.count), valueText: $0.count.formatted(),
                                  color: Palette.series[2])
                        })
                    }
                }
            }
            .padding(20)
        }
        .defaultScrollAnchor(CommandLine.arguments.contains("--scroll-bottom") ? .bottom : .top)
    }
}

// MARK: - Models

struct ModelsPage: View {
    @EnvironmentObject var app: AppState
    @State private var sort = [KeyPathComparator(\ModelRowItem.total, order: .reverse)]
    @State private var selection: String?

    struct ModelRowItem: Identifiable {
        let m: ModelTotal
        var id: String { m.model }
        var name: String { ModelNames.display(m.model) }
        var total: Int { m.totals.all }
        var input: Int { m.totals.input }
        var output: Int { m.totals.output }
        var cacheRead: Int { m.totals.cacheRead }
        var cacheWrite: Int { m.totals.cacheWrite }
        var requests: Int { m.totals.requests }
        var cost: Double { m.totals.cost }
        var lastUsed: Date { m.lastUsed }
    }

    var body: some View {
        let rows = app.data.models.map(ModelRowItem.init).sorted(using: sort)
        VSplitView {
            ScrollView {
                Card(title: selection.map { "\(ModelNames.display($0)) · tokens per \(app.range == .today ? "hour" : "day")" } ?? "Output tokens per model",
                     subtitle: selection == nil ? "Select a model in the table to see its own history" : "Input + output") {
                    if selection != nil {
                        Button { selection = nil } label: { Label("All models", systemImage: "chevron.left") }
                            .controlSize(.small)
                    }
                    UsageChart(points: app.data.buckets, metric: selection == nil ? .output : .inOut,
                               hourly: app.range == .today, focusModel: selection, height: 220)
                }
                .padding(20)
            }
            .frame(minHeight: 320, idealHeight: 380)

            Table(rows, selection: $selection, sortOrder: $sort) {
                TableColumn("Model", value: \.name) { r in
                    HStack(spacing: 6) {
                        Circle().fill(app.color(for: r.m.model)).frame(width: 8, height: 8)
                        Text(r.name).fontWeight(.medium)
                    }
                    .help(r.m.model)
                }
                .width(min: 130, ideal: 170)
                TableColumn("Via") { r in
                    Text(sourceLabels(r.m.sources) + " · " + r.m.providers).foregroundStyle(.secondary).help(r.m.providers)
                }
                .width(min: 110, ideal: 180)
                TableColumn("Requests", value: \.requests) { Text($0.requests.formatted()).monospacedDigit() }.width(66)
                TableColumn("Input", value: \.input) { Text(Fmt.tokens($0.input)).monospacedDigit() }.width(62)
                TableColumn("Output", value: \.output) { Text(Fmt.tokens($0.output)).monospacedDigit() }.width(62)
                TableColumn("Cache read", value: \.cacheRead) { Text(Fmt.tokens($0.cacheRead)).monospacedDigit() }.width(76)
                TableColumn("Cache write", value: \.cacheWrite) { Text(Fmt.tokens($0.cacheWrite)).monospacedDigit() }.width(76)
                TableColumn("Total", value: \.total) { Text(Fmt.tokens($0.total)).monospacedDigit().fontWeight(.medium) }.width(66)
                TableColumn("Est. cost", value: \.cost) { Text(Fmt.cost($0.cost)).monospacedDigit() }.width(66)
                TableColumn("Last used", value: \.lastUsed) { Text($0.lastUsed, format: .relative(presentation: .named)).foregroundStyle(.secondary) }
                    .width(min: 80, ideal: 100)
            }
            .frame(minHeight: 200)
        }
    }
}

// MARK: - Sessions

struct SessionsPage: View {
    @EnvironmentObject var app: AppState
    @State private var sort = [KeyPathComparator(\SessionSummary.end, order: .reverse)]
    @State private var selection: SessionSummary.ID?

    var body: some View {
        let search = app.sessionSearch
        let rows = app.data.sessions.filter { s in
            search.isEmpty || [s.title ?? "", s.project, s.id, s.models.joined(separator: " ")]
                .contains { $0.localizedCaseInsensitiveContains(search) }
        }.sorted(using: sort)

        Table(rows, selection: $selection, sortOrder: $sort) {
            TableColumn("") { s in
                Circle().fill(s.isActive ? Palette.good : Color.clear).frame(width: 7, height: 7)
                    .helpIfPresent(s.isActive ? "Active in the last 10 minutes" : nil)
            }
            .width(12)
            TableColumn("Session") { s in
                Text(s.displayTitle).lineLimit(1).help(s.displayTitle)
            }
            .width(min: 140, ideal: 230)
            TableColumn("Project") { Text($0.projectName).helpIfPresent($0.project) }.width(min: 70, ideal: 110)
            TableColumn("Agent") { s in Label(s.source.shortLabel, systemImage: s.source.symbol) }.width(min: 70, ideal: 80)
            TableColumn("Models") { s in
                HStack(spacing: 4) {
                    ForEach(s.models.prefix(2), id: \.self) { m in
                        Text(ModelNames.display(m)).font(.caption).lineLimit(1)
                            .padding(.horizontal, 5).padding(.vertical, 1)
                            .background(Capsule().fill(app.color(for: m).opacity(0.18)))
                    }
                    if s.models.count > 2 { Text("+\(s.models.count - 2)").font(.caption).foregroundStyle(.secondary) }
                }
                .help(s.models.map(ModelNames.display).joined(separator: ", "))
            }
            .width(min: 90, ideal: 130)
            TableColumn("Last active", value: \.end) { Text($0.end, format: .dateTime.month(.abbreviated).day().hour().minute()).monospacedDigit() }
                .width(min: 95, ideal: 110)
            TableColumn("Duration", value: \.duration) { Text(Fmt.duration($0.duration)).monospacedDigit() }.width(62)
            TableColumn("Req.", value: \.requests) { Text("\($0.requests)").monospacedDigit() }.width(44)
            TableColumn("Tokens", value: \.tokens) { Text(Fmt.tokens($0.tokens)).monospacedDigit() }.width(60)
            TableColumn("Cost", value: \.cost) { Text(Fmt.cost($0.cost)).monospacedDigit() }.width(60)
        }
        .searchable(text: $app.sessionSearch, prompt: "Title, project, model…")
        .overlay {
            if rows.isEmpty {
                ContentUnavailableView.search(text: search)
            }
        }
        .inspector(isPresented: Binding(get: { selection != nil }, set: { if !$0 { selection = nil } })) {
            if let s = rows.first(where: { $0.id == selection }) ?? app.data.sessions.first(where: { $0.id == selection }) {
                SessionInspector(session: s)
                    .inspectorColumnWidth(min: 280, ideal: 320, max: 420)
            }
        }
    }
}

struct SessionInspector: View {
    @EnvironmentObject var app: AppState
    let session: SessionSummary
    @State private var detail = SessionDetail()

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                VStack(alignment: .leading, spacing: 4) {
                    HStack {
                        Label(session.source.label, systemImage: session.source.symbol).font(.caption).foregroundStyle(.secondary)
                        if session.isActive {
                            Text("Active").font(.caption2.weight(.semibold)).foregroundStyle(Palette.good)
                        }
                    }
                    Text(session.displayTitle).font(.title3.weight(.semibold)).textSelection(.enabled)
                    Text(session.id).font(.caption2.monospaced()).foregroundStyle(.tertiary).textSelection(.enabled)
                }

                Grid(alignment: .leading, horizontalSpacing: 12, verticalSpacing: 6) {
                    row("Project", detail.cwd ?? session.project)
                    row("Started", session.start.formatted(date: .abbreviated, time: .shortened))
                    row("Last active", session.end.formatted(date: .abbreviated, time: .shortened))
                    row("Duration", Fmt.duration(session.duration))
                    row("Requests", session.requests.formatted())
                    row("Tokens", "\(Fmt.tokens(session.tokens)) (\(Fmt.tokens(session.output)) output)")
                    row("Est. cost", Fmt.cost(session.cost))
                    if !detail.kinds.isEmpty {
                        row("Calls", detail.kinds.map { "\($0.count) \($0.name)" }.joined(separator: " · "))
                    }
                }
                .font(.callout)

                if !detail.models.isEmpty {
                    Text("Models").font(.headline)
                    RankedBars(items: detail.models.map {
                        .init(id: $0.model, label: ModelNames.display($0.model), value: Double($0.totals.all),
                              valueText: "\(Fmt.tokens($0.totals.all)) · \(Fmt.cost($0.totals.cost))",
                              color: app.namedModels.contains($0.model) ? app.color(for: $0.model) : Palette.other,
                              help: "in \(Fmt.tokens($0.totals.input)) · out \(Fmt.tokens($0.totals.output)) · cache read \(Fmt.tokens($0.totals.cacheRead)) · cache write \(Fmt.tokens($0.totals.cacheWrite))")
                    })
                }
                if !detail.tools.isEmpty {
                    Text("Tools").font(.headline)
                    RankedBars(items: detail.tools.prefix(12).map {
                        .init(id: $0.name, label: $0.name, value: Double($0.count), valueText: "\($0.count)", color: Palette.series[2])
                    })
                }
            }
            .padding(16)
            .frame(maxWidth: .infinity, alignment: .leading)
        }
        .task(id: session.id) {
            if let store = app.store { detail = await store.sessionDetail(session.id) }
        }
    }

    @ViewBuilder
    private func row(_ label: String, _ value: String) -> some View {
        GridRow {
            Text(label).foregroundStyle(.secondary)
            Text(value).textSelection(.enabled).lineLimit(3)
        }
    }
}

// MARK: - Projects

struct ProjectsPage: View {
    @EnvironmentObject var app: AppState

    var body: some View {
        ScrollView {
            Card(title: "Projects", subtitle: "Working directories the agents ran in · click one to see its sessions") {
                RankedBars(items: app.data.projects.prefix(60).map {
                    .init(id: $0.path, label: $0.displayName ?? $0.name, value: Double($0.tokens),
                          valueText: "\(Fmt.tokens($0.tokens)) · \(Fmt.cost($0.cost))",
                          detail: "\(plural($0.sessions, "session")) · \(sourceLabels($0.sources)) · \($0.lastUsed.formatted(.relative(presentation: .named)))",
                          help: $0.path)
                }) { app.showSessions(matching: $0.label) }
            }
            .padding(20)
        }
    }
}

// MARK: - Limits

struct LimitsPage: View {
    @EnvironmentObject var app: AppState

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                ProviderGrid()

                Card(title: "Quota usage over time", subtitle: "Recorded by this app while it runs (last 14 days) · hover for values") {
                    if app.data.limitHistory.isEmpty {
                        Text("History builds up while Burnrate is running.").foregroundStyle(.secondary)
                    } else {
                        LimitHistoryChart(points: app.data.limitHistory,
                                          activeKeys: Set(app.providerList.flatMap { $0.windows.map(\.id) }))
                    }
                }

                Card(title: "Claude Code — last 5 hours", subtitle: "Local usage behind the current session window") {
                    let b = app.data.claudeLast5h
                    Grid(alignment: .leading, horizontalSpacing: 24, verticalSpacing: 6) {
                        GridRow { Text("Tokens").foregroundStyle(.secondary); Text(Fmt.tokens(b.all)) }
                        GridRow { Text("Output").foregroundStyle(.secondary); Text(Fmt.tokens(b.output)) }
                        GridRow { Text("Requests").foregroundStyle(.secondary); Text(b.requests.formatted()) }
                        GridRow { Text("API-equivalent cost").foregroundStyle(.secondary); Text(Fmt.cost(b.cost)) }
                        if let tier = app.limits.tier {
                            GridRow { Text("Rate-limit tier").foregroundStyle(.secondary); Text(tier) }
                        }
                    }
                    .font(.callout)
                }
            }
            .padding(20)
        }
    }
}

// MARK: - Help

struct HelpPage: View {
    @EnvironmentObject var app: AppState
    @State private var exportMessage: String?

    private let home = FileManager.default.homeDirectoryForCurrentUser.path

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                Card(title: "How Burnrate works") {
                    Text("""
                    Everything is read from your disk. The agents already write a log line for every model response, \
                    including model, token counts and (for pi/omp) cost. Burnrate reads only the new lines, keeps them \
                    in its own database, and builds the dashboard from that database. Only the quota cards use the network: \
                    they ask Anthropic, GitHub and OpenRouter for your current limits, reusing the logins those tools already have.
                    """)
                    .fixedSize(horizontal: false, vertical: true)
                }

                Card(title: "Startup", subtitle: "Keep quota history continuous") {
                    LoginItemToggle()
                    Text("When on, Burnrate starts quietly in the menu bar at login and is restarted automatically if it ever crashes. Quitting it from the menu keeps it closed until the next login.")
                        .font(.caption).foregroundStyle(.secondary).fixedSize(horizontal: false, vertical: true)
                }

                Card(title: "Refresh schedule") {
                    Grid(alignment: .leading, horizontalSpacing: 20, verticalSpacing: 8) {
                        GridRow {
                            Text("What").foregroundStyle(.secondary); Text("Every").foregroundStyle(.secondary)
                            Text("Last run").foregroundStyle(.secondary)
                        }
                        .font(.caption)
                        Divider().gridCellColumns(3)
                        scheduleRow("Session logs (Claude Code, pi, omp)", Refresh.files, app.lastScan)
                        scheduleRow("Claude plan limits", Refresh.claude, app.lastAttempt[.claude])
                        scheduleRow("GitHub Copilot quota", Refresh.copilot, app.lastAttempt[.copilot])
                        scheduleRow("OpenRouter credits and limits", Refresh.openRouter, app.lastAttempt[.openRouter])
                    }
                    .font(.callout)
                    Text("⌘R refreshes everything now (quota endpoints at most once every \(Int(Refresh.manualMinimum))s). After errors the app backs off, up to \(Int(Refresh.maxBackoff / 60)) minutes.")
                        .font(.caption).foregroundStyle(.secondary)
                }

                Card(title: "Your data is kept", subtitle: "Nothing is deleted when the source files are") {
                    if let st = app.dbStats {
                        Grid(alignment: .leading, horizontalSpacing: 20, verticalSpacing: 6) {
                            statRow("Database", st.path.replacingOccurrences(of: home, with: "~"))
                            statRow("Size", ByteCountFormatter.string(fromByteCount: Int64(st.bytes), countStyle: .file))
                            statRow("History since", st.oldest?.formatted(date: .long, time: .omitted) ?? "—")
                            statRow("Model responses", st.usageRows.formatted())
                            statRow("Sessions", st.sessions.formatted())
                            statRow("Tool calls", st.toolCalls.formatted())
                            statRow("Quota readings", st.snapshots.formatted())
                            statRow("Session files tracked", "\(st.trackedFiles.formatted())" + (st.missingFiles > 0 ? " · \(st.missingFiles) deleted since, data kept" : ""))
                            if st.archiveDays > 0 {
                                statRow("Imported archive", "\(plural(st.archiveDays, "day")) from Claude Code's stats cache")
                            }
                        }
                        .font(.callout)
                    } else {
                        ProgressView().controlSize(.small)
                    }
                    Text("""
                    Stored per model response: time, agent, session, project folder, provider, model, input/output/cache \
                    tokens, reasoning tokens and cost. Also stored: session titles, tool names used, and every quota reading. \
                    Not stored: prompts, replies, file contents or any credentials.
                    """)
                    .font(.caption).foregroundStyle(.secondary).fixedSize(horizontal: false, vertical: true)
                    HStack {
                        Button("Show in Finder") {
                            NSWorkspace.shared.activateFileViewerSelecting([URL(fileURLWithPath: Store.defaultPath)])
                        }
                        Button("Export usage as CSV…") { export() }
                        if let exportMessage { Text(exportMessage).font(.caption).foregroundStyle(.secondary) }
                    }
                }

                Card(title: "Data sources") {
                    Grid(alignment: .leading, horizontalSpacing: 16, verticalSpacing: 10) {
                        sourceRow("Claude Code", "~/.claude/projects/**/*.jsonl",
                                  "Tokens per response incl. sub-agents; advisor calls counted on their own model. Cost estimated at API list prices.",
                                  exists: "\(home)/.claude/projects")
                        sourceRow("Claude Code archive", "~/.claude/stats-cache.json",
                                  "Daily per-model totals for days whose transcripts are already gone. Per-model totals are exact; the split across days of cache tokens is estimated.",
                                  exists: "\(home)/.claude/stats-cache.json")
                        sourceRow("pi", "~/.pi/agent/sessions/**/*.jsonl", "Tokens and the cost pi reports.",
                                  exists: "\(home)/.pi/agent/sessions")
                        sourceRow("omp", "~/.omp/agent/sessions/**/*.jsonl", "Tokens and the cost omp reports; sub-agents roll up to their parent session.",
                                  exists: "\(home)/.omp/agent/sessions")
                        sourceRow("Claude limits", "api.anthropic.com · Claude Code login (Keychain)",
                                  "Session (5h), weekly and per-model limits, extra usage. The token is only read, never refreshed. The endpoint's rate limit is shared with other tools that poll it (such as the oh-my-claudecode HUD); when it says \"rate limited\", a recent reading from that HUD's cache is used.", exists: nil)
                        sourceRow("Copilot quota", "api.github.com · omp/pi Copilot login",
                                  "Monthly premium requests used and remaining.", exists: nil)
                        sourceRow("OpenRouter", "openrouter.ai · every key omp and pi hold",
                                  "Account credits, key spend limit, free-model daily requests, daily/weekly/monthly spend.", exists: nil)
                    }
                    .font(.callout)
                }

                Card(title: "Tips") {
                    VStack(alignment: .leading, spacing: 8) {
                        tip("clock.arrow.circlepath", "Claude Code deletes transcripts after 30 days by default. Token usage is safe as long as Burnrate opens at least once before a file is deleted, because each launch reads everything still on disk. Quota history (the limit percentages) is only recorded while the app is running, so launching it at login gives a continuous record. Setting \"cleanupPeriodDays\" in ~/.claude/settings.json keeps the transcripts themselves longer.")
                        tip("dollarsign.circle", "Claude Code costs are what the same tokens would cost on the pay-as-you-go API. They show the value you get from the subscription, not a bill. Prices live in Pricing.table (Models.swift).")
                        tip("cursorarrow.rays", "Hover charts for details, click a project to see its sessions, click an agent to filter, and select a session or model for more.")
                        tip("menubar.rectangle", "The menu bar shows the Claude 5-hour session percentage. Click it for all quotas and today's totals.")
                    }
                }
            }
            .padding(20)
            .frame(maxWidth: 900, alignment: .leading)
            .frame(maxWidth: .infinity)
        }
        .onAppear { app.refreshStats() }
    }

    @ViewBuilder
    private func scheduleRow(_ what: String, _ every: TimeInterval, _ last: Date?) -> some View {
        GridRow {
            Text(what)
            Text(every < 60 ? "\(Int(every)) s" : "\(Int(every / 60)) min").monospacedDigit()
            Text(last.map { $0.formatted(.relative(presentation: .named)) } ?? "not yet").foregroundStyle(.secondary)
        }
    }

    @ViewBuilder
    private func statRow(_ label: String, _ value: String) -> some View {
        GridRow {
            Text(label).foregroundStyle(.secondary)
            Text(value).textSelection(.enabled)
        }
    }

    @ViewBuilder
    private func sourceRow(_ name: String, _ location: String, _ what: String, exists path: String?) -> some View {
        GridRow(alignment: .top) {
            HStack(spacing: 5) {
                if let path {
                    let ok = FileManager.default.fileExists(atPath: path)
                    Image(systemName: ok ? "checkmark.circle.fill" : "minus.circle").foregroundStyle(ok ? Palette.good : .secondary)
                        .help(ok ? "Found" : "Not found on this Mac")
                } else {
                    Image(systemName: "network").foregroundStyle(.secondary)
                }
                Text(name).fontWeight(.medium)
            }
            VStack(alignment: .leading, spacing: 2) {
                Text(location).font(.caption.monospaced()).foregroundStyle(.secondary).textSelection(.enabled)
                Text(what).fixedSize(horizontal: false, vertical: true)
            }
        }
    }

    @ViewBuilder
    private func tip(_ symbol: String, _ text: String) -> some View {
        Label { Text(text).fixedSize(horizontal: false, vertical: true) } icon: { Image(systemName: symbol).foregroundStyle(Palette.series[0]) }
            .font(.callout)
    }

    private func export() {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.commaSeparatedText]
        panel.nameFieldStringValue = "token-usage-\(Date().formatted(.iso8601.year().month().day())).csv"
        guard panel.runModal() == .OK, let url = panel.url, let store = app.store else { return }
        Task {
            do {
                let n = try await store.exportCSV(to: url)
                exportMessage = "Exported \(n.formatted()) rows"
            } catch {
                exportMessage = "Export failed: \(error.localizedDescription)"
            }
        }
    }
}
